apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploy-b
spec: 
replicas: 2
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
      - name: app-b
        image: brendalmalves/app-b
        ports:
        - containerPort: 5000