FROM ubuntu:latest

RUN apt-get update -y
RUN apt-get install python3 python3-pip git -y
RUN pip install flask
RUN pip install cryptography
RUN pip install requests

WORKDIR /app

COPY . .

EXPOSE 5000

CMD flask --app main.py run -h 0.0.0.0