apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploy-a
spec: 
replicas: 2
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: app-a
        image: brendalmalves/app-a