FROM ubuntu:latest

RUN apt-get update -y
RUN apt-get install python3 python3-pip git -y
RUN pip install flask
RUN pip install cryptography
RUN pip install requests

WORKDIR /app

COPY . .

CMD [ "python3", "main.py"]